version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.pwa
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  # Example backend service placeholder - replace with your real backend image/command
  backend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "cd server && npm run start"
    ports:
      - "5000:5000"
